; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
targets = compiledb
build_type = debug
board_build.ldscript = STM32F103C8TX_FLASH.ld
; CPU runs at 72MHz derived from 8MHz HSE
build_flags =
  -D HSE_VALUE=8000000
  -D USBD_USE_CDC
  -D HAL_PCD_MODULE_ENABLED
  -D USE_USB_FS
